# Generated by Django 3.0.5 on 2020-07-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200702_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
