# Generated by Django 3.0.7 on 2020-07-16 09:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200716_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='context',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
